#!/usr/bin/perl
=head1 NAME

 Hello  world

=cut

use strict;
use warnings;
require Abills::Misc;
use A_module;
use Conf;
use Data::Dumper;


# Модуль конфигурации

our (
  $db,
  $admin,
  %conf,
  # $libpath,
  %lang,
  %FORM,
  $index,
);


our Abills::HTML $html;
my Abills::HTML $table;

my $A_module = A_module->new($db, $admin, \%conf);

#*******************************************************************
=head2 first_function()

=cut
#*******************************************************************
sub first_function {
  print $html->message('info', $lang{INFO}, "Hello world from FIRST function");
}

#*******************************************************************
=head2 second_function ($attr) - show list of customers with options 'add', 'edit' and 'delete'

=cut
#*******************************************************************
sub second_function {

  if ($FORM{add}) {
    $A_module->customer_add(\%FORM);
    $html->message('success', $lang{COMPETITOR_ADDED}) if (!_error_show($A_module));
  }
  elsif ($FORM{chg}) {
    $A_module->{ACTION} = 'change';
    $A_module->{LNG_ACTION} = $lang{CHANGE};

    $A_module->customer_info({ ID => $FORM{chg} });
    $FORM{add_form}=1
  }
  elsif ($FORM{change}) {
    $A_module->customer_change(\%FORM);
    $html->message('success', $lang{COMPETITOR_CHANGED}) if (!_error_show($A_module));
  }
  elsif ($FORM{del}) {
    $A_module->customer_del({ ID => $FORM{del} });
    $html->message('success', $lang{COMPETITOR_DELETED})  if (!_error_show($A_module));
  }

  if ($FORM{add_form}) {
    print $html->message('info', $lang{INFO}, "Please fill the fields");
    print $html->tpl_show(_include('A_module_form_tp', 'A_module'), {
      INDEX => $index,
      ACTION => 'add',
      LNG_ACTION => $lang{ADD},
      %$A_module
    }, { OUTPUT2RETURN => 1 });
  }

  my $customer_list = $A_module->customer_list({ COLS_NAME => 1 });

  $table = $html->table({
    width   => '100%',
    caption => "List of customers",
    title   => [ "ID", $lang{NAME}, $lang{ADDRESS_STREET}],
    cols_align => ['center', 'right', 'left'],
    pages   => 20,
    ID      => 'LIST_ID',
    HAS_FUNCTION_FIELDS => 1,
    MENU    => "$lang{ADD}:index=$index&add_form=1:add",
  });

  foreach my $line (@$customer_list) {
    $table->addrow(
      $line->{id},
      $line->{name},
      $line->{address_street},
      $html->button('Edit', "index=$index&chg=$line->{id}",{ class => 'change' }),
      $html->button('Delete', "index=$index&del=$line->{id}",
        { MESSAGE => "$lang{DEL} $line->{name}? $line->{address_street}?", class => 'del' }),
    );
  }

  print $table->show();

  return 1;
}

1;

